url: https://www.cata.dev
baseurl: ''
title: Catalin Ciocov

plugins:
  - jekyll-postcss

postcss:
  cache: false

exclude:
  - package-lock.json
  - package.json
  - postcss.config.js
  - tailwind.config.js
